=== Varnahg/ReverseClinic/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- 1. pattern -->
  <xs:simpleType name="kodOddeleniType">
    <xs:annotation>
      <xs:documentation>Kod oddeleni musi byt presne 3 velka pismena (napr. INT)</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{3}"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- 2. enumeration -->
  <xs:simpleType name="cisloPojistovnyType">
    <xs:annotation>
      <xs:documentation>Cislo pojistovny â€“ povolene hodnoty: 111, 205, 207, 213</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="111"/>
      <xs:enumeration value="205"/>
      <xs:enumeration value="207"/>
      <xs:enumeration value="213"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- 3. minLength -->
  <xs:simpleType name="rodneCisloType">
    <xs:annotation>
      <xs:documentation>Rodne cislo musi mit alespon 11 znaku (napr. 850101/1234)</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:minLength value="11"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- 4. maxInclusive -->
  <xs:simpleType name="kapacitaType">
    <xs:annotation>
      <xs:documentation>Maximalni kapacita luzek je 100</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:integer">
      <xs:maxInclusive value="100"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- 5. whiteSpace -->
  <xs:simpleType name="telefonCisty">
    <xs:annotation>
      <xs:documentation>Telefonni cislo bude automaticky orezano od nadbytecnych mezer</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Struktura kliniky -->
  <xs:element name="klinika">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="oddeleni">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nazevOddeleni" type="xs:string"/>
              <xs:element name="adresaOddeleni" type="xs:string"/>
              <xs:element name="kapacitaLuzek" type="kapacitaType"/>
              <xs:element name="lekar" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="titul" type="xs:string"/>
                    <xs:element name="jmeno" type="xs:string"/>
                    <xs:element name="prijmeni" type="xs:string"/>
                    <xs:element name="specializace" type="xs:string"/>
                    <xs:element name="email" type="xs:string"/>
                    <xs:element name="telefon" type="telefonCisty"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required"/>
                  <xs:attribute name="smluvni" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="pacient" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="jmeno" type="xs:string"/>
                    <xs:element name="prijmeni" type="xs:string"/>
                    <xs:element name="rodneCislo" type="rodneCisloType"/>
                    <xs:element name="datumNarozeni" type="xs:date"/>
                    <xs:element name="pohlavi" type="xs:string"/>
                    <xs:element name="pojistovna" type="cisloPojistovnyType"/>
                    <xs:element name="statniPrislusnost" type="xs:string"/>
                    <xs:element name="telefon" type="telefonCisty"/>
                    <xs:element name="email" type="xs:string"/>
                    <xs:element name="adresa" type="xs:string"/>
                    <xs:element name="kontaktniOsoba" type="xs:string"/>
                    <xs:element name="alergie" type="xs:string"/>
                    <xs:element name="zaznamy">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="zaznam" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="typ" type="xs:string"/>
                                <xs:element name="datum" type="xs:date"/>
                                <xs:element name="cas" type="xs:string"/>
                                <xs:element name="diagnoza" type="xs:string"/>
                                <xs:element name="ukon" type="xs:string"/>
                                <xs:element name="lekarId" type="xs:string"/>
                                <xs:element name="oddeleniKod" type="kodOddeleniType"/>
                                <xs:element name="poznamka" type="xs:string"/>
                                <xs:element name="hospitalizace" type="xs:boolean"/>
                                <xs:element name="predpis" type="xs:string"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required"/>
                  <xs:attribute name="stav" type="xs:string"/>
                  <xs:attribute name="rizikovy" type="xs:string"/>
                  <xs:attribute name="pojisten" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="kod" type="kodOddeleniType"/>
            <xs:attribute name="typ" type="xs:string"/>
            <xs:attribute name="patro" type="xs:string"/>
            <xs:attribute name="otevreno" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Varnahg/ReverseClinic/data.xml
<?xml version='1.0' encoding='UTF-8'?>
<klinika xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
  <oddeleni kod="INT" typ="interni" patro="2" otevreno="true">
    <nazevOddeleni>Interna</nazevOddeleni>
    <adresaOddeleni>Nemocnicni 12, Brno</adresaOddeleni>
    <kapacitaLuzek>45</kapacitaLuzek>
    <lekar id="L001" smluvni="true">
      <titul>MUDr.</titul>
      <jmeno>Eva</jmeno>
      <prijmeni>Novotna</prijmeni>
      <specializace>Kardiologie</specializace>
      <email>eva.novotna@klinika.cz</email>
      <telefon>123456789</telefon>
    </lekar>
    <!-- 5 pacientu s ruznymi zaznamy -->
    
<pacient id="P001" stav="aktivni" rizikovy="false" pojisten="true">
  <jmeno>Jan</jmeno>
  <prijmeni>Novak</prijmeni>
  <rodneCislo>850101/1234</rodneCislo>
  <datumNarozeni>1985-01-01</datumNarozeni>
  <pohlavi>M</pohlavi>
  <pojistovna>111</pojistovna>
  <statniPrislusnost>Ceska republika</statniPrislusnost>
  <telefon>+420123456P001</telefon>
  <email>jan.novak@email.cz</email>
  <adresa>Ulice 1, Mesto</adresa>
  <kontaktniOsoba>Anna Novakova</kontaktniOsoba>
  <alergie>Penicilin</alergie>
  <zaznamy>
    <zaznam>
      <typ>navsteva</typ>
      <datum>2025-03-01</datum>
      <cas>09:30</cas>
      <diagnoza>J45</diagnoza>
      <ukon>Penis Reduction</ukon>
      <lekarId>L001</lekarId>
      <oddeleniKod>INT</oddeleniKod>
      <poznamka>dusnost</poznamka>
      <hospitalizace>false</hospitalizace>
      <predpis>Ventolin</predpis>
    </zaznam>
  </zaznamy>
</pacient>


<pacient id="P002" stav="propusten" rizikovy="false" pojisten="true">
  <jmeno>Petra</jmeno>
  <prijmeni>Dvorakova</prijmeni>
  <rodneCislo>900202/4567</rodneCislo>
  <datumNarozeni>1990-02-02</datumNarozeni>
  <pohlavi>F</pohlavi>
  <pojistovna>205</pojistovna>
  <statniPrislusnost>Ceska republika</statniPrislusnost>
  <telefon>+420123456P002</telefon>
  <email>petra@email.cz</email>
  <adresa>Ulice 2, Mesto</adresa>
  <kontaktniOsoba>Jan Dvorak</kontaktniOsoba>
  <alergie>Zadne</alergie>
  <zaznamy>
    <zaznam>
      <typ>kontrola</typ>
      <datum>2025-03-05</datum>
      <cas>10:15</cas>
      <diagnoza>Z09</diagnoza>
      <ukon>Wrinkle Restoration</ukon>
      <lekarId>L001</lekarId>
      <oddeleniKod>INT</oddeleniKod>
      <poznamka>v poradku</poznamka>
      <hospitalizace>false</hospitalizace>
      <predpis>---</predpis>
    </zaznam>
  </zaznamy>
</pacient>


<pacient id="P003" stav="hospitalizovan" rizikovy="true" pojisten="false">
  <jmeno>Lukas</jmeno>
  <prijmeni>Krejci</prijmeni>
  <rodneCislo>920303/7890</rodneCislo>
  <datumNarozeni>1992-03-03</datumNarozeni>
  <pohlavi>M</pohlavi>
  <pojistovna>213</pojistovna>
  <statniPrislusnost>Ceska republika</statniPrislusnost>
  <telefon>+420123456P003</telefon>
  <email>lukas@email.cz</email>
  <adresa>Ulice 3, Mesto</adresa>
  <kontaktniOsoba>Alena Krejci</kontaktniOsoba>
  <alergie>Vceli bodnuti</alergie>
  <zaznamy>
    <zaznam>
      <typ>vysetreni</typ>
      <datum>2025-03-10</datum>
      <cas>11:00</cas>
      <diagnoza>R51</diagnoza>
      <ukon>Reverse Liposuction</ukon>
      <lekarId>L001</lekarId>
      <oddeleniKod>INT</oddeleniKod>
      <poznamka>bolest hlavy</poznamka>
      <hospitalizace>true</hospitalizace>
      <predpis>Paralen</predpis>
    </zaznam>
  </zaznamy>
</pacient>


<pacient id="P004" stav="aktivni" rizikovy="true" pojisten="true">
  <jmeno>Martina</jmeno>
  <prijmeni>Benesova</prijmeni>
  <rodneCislo>880404/2345</rodneCislo>
  <datumNarozeni>1988-04-04</datumNarozeni>
  <pohlavi>F</pohlavi>
  <pojistovna>111</pojistovna>
  <statniPrislusnost>Ceska republika</statniPrislusnost>
  <telefon>+420123456P004</telefon>
  <email>martina@email.cz</email>
  <adresa>Ulice 4, Mesto</adresa>
  <kontaktniOsoba>Eva Benesova</kontaktniOsoba>
  <alergie>Gluten</alergie>
  <zaznamy>
    <zaznam>
      <typ>konzultace</typ>
      <datum>2025-03-12</datum>
      <cas>14:00</cas>
      <diagnoza>E66</diagnoza>
      <ukon>Acne Revival</ukon>
      <lekarId>L001</lekarId>
      <oddeleniKod>INT</oddeleniKod>
      <poznamka>nadvaha</poznamka>
      <hospitalizace>false</hospitalizace>
      <predpis>Doporuceni</predpis>
    </zaznam>
  </zaznamy>
</pacient>


<pacient id="P005" stav="ceka" rizikovy="false" pojisten="false">
  <jmeno>Tomas</jmeno>
  <prijmeni>Svoboda</prijmeni>
  <rodneCislo>950505/6789</rodneCislo>
  <datumNarozeni>1995-05-05</datumNarozeni>
  <pohlavi>M</pohlavi>
  <pojistovna>207</pojistovna>
  <statniPrislusnost>Ceska republika</statniPrislusnost>
  <telefon>+420123456P005</telefon>
  <email>tomas@email.cz</email>
  <adresa>Ulice 5, Mesto</adresa>
  <kontaktniOsoba>Karel Svoboda</kontaktniOsoba>
  <alergie>Laktoza</alergie>
  <zaznamy>
    <zaznam>
      <typ>navsteva</typ>
      <datum>2025-03-20</datum>
      <cas>08:00</cas>
      <diagnoza>K21</diagnoza>
      <ukon>Wrinkle Restoration</ukon>
      <lekarId>L001</lekarId>
      <oddeleniKod>INT</oddeleniKod>
      <poznamka>nevolnost</poznamka>
      <hospitalizace>true</hospitalizace>
      <predpis>Omeprazol</predpis>
    </zaznam>
  </zaznamy>
</pacient>

  </oddeleni>
</klinika>
